/** Generated by KPC **/
KISSY.config('modules', {
    'xcake/app/cjs-full': {
        'requires': [
            'node',
            '../components/header/',
            './mod/',
            './example.css'
        ]
    },
    'xcake/app/cjs': {
        'requires': [
            'node',
            '../components/header/',
            './mod/',
            './example.css'
        ]
    },
    'xcake/app/fac-config': { 'requires': ['node'] },
    'xcake/app/namedMod2': {
        'requires': [
            'node',
            './mod'
        ]
    },
    'xcake/pages/home/index': {
        'requires': [
            'node',
            'xcake/app/',
            './page.css',
            'xcake/components/slide/'
        ]
    }
});
