/** Generated by KPC **/
KISSY.config('modules', {
    'xcake/app/cjs-full': {
        'requires': [
            'node',
            '../components/header/',
            './mod/',
            './example.css'
        ]
    },
    'xcake/app/cjs': {
        'requires': [
            'node',
            '../components/header/',
            './mod/',
            './example.css'
        ]
    }
});
