/** Generated by KPC **/
KISSY.config('modules', {
    'xcake/app/cjs-full': {
        'requires': [
            'node',
            '../pages/home/',
            './cjs',
            './example.css'
        ]
    },
    'xcake/app/cjs': {
        'requires': [
            'node',
            '../pages/home/',
            './cjs-full',
            './example.css'
        ]
    },
    'xcake/app/fac-config': { 'requires': ['node'] },
    'xcake/app/name-fac-config': {
        'requires': [
            'node',
            './cjs-full'
        ]
    },
    'xcake/pages/home/index': {
        'requires': [
            'node',
            'xcake/app/cjs',
            './mod',
            './page.css'
        ]
    }
});
