/** Generated by node-kpc **/
KISSY.config('modules', {
    '_/components/button/index': {
        'requires': [
            'base',
            'node',
            'base',
            'gallery/button/1.0/index'
        ]
    },
    '_/components/sidebar/index': {
        'requires': [
            '_/components/button/index',
            'node'
        ]
    },
    '_/pages/home/index-m': { 'requires': ['_/components/sidebar/index'] },
    '_/pages/home/index': {
        'requires': [
            '_/components/sidebar/index',
            'node'
        ]
    }
});